### ISSUE TITLE
vue-echarts 解决方案

### ISSUE THREAD

**Issue by vhxubo** [vhxubo/blog#1]
## 图表自适应

> https://github.com/ecomfe/vue-echarts/issues/421

- 设置父组件高度
- 设置图表样式

```css
.echarts {
  width: 100%;
  height: 100%;
}
```
- 增加 `autoresize` prop

## 运行 Demo

> https://github.com/ecomfe/vue-echarts/issues/474#issuecomment-717636315

- 删除`package-lock.json`

```
npm i
npm serve
```
