### ISSUE TITLE
Vue 2

### ISSUE THREAD

**Issue by vhxubo** [vhxubo/blog#63]
## 解决 Vue 变量未渲染前代码显示问题
> https://cn.vuejs.org/v2/api/index.html?#v-cloak

```css
[v-cloak] {
  display: none;
}
```
```html
<div v-cloak>
  {{ message }}
</div>
```
